before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby  
rvm:
  - "2.2.0"
services:
  - mongodb
addons:
  code_climate:
    repo_token: f9db36d7a7ecf741c3e3acfc50652c662ae233d532ebefd99ba394caa290a98b
script:
  - cd dummy
  - ln -s ../.git .git
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=f9db36d7a7ecf741c3e3acfc50652c662ae233d532ebefd99ba394caa290a98b bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=f9db36d7a7ecf741c3e3acfc50652c662ae233d532ebefd99ba394caa290a98b bundle exec cucumber
